backend/addresses/urls.py
from django.urls import path, include



from addresses.views import *

app_name = 'addresses'

urlpatterns = [
    path('',
         AddressListView.as_view(), name='address_list'),
    path('add/',
         AddressCreateView.as_view(), name='address_add'),
    path('view/<int:pk>/',
         AddressDetailView.as_view(), name='address_view'),
    path('change/<int:pk>/',
         AddressUpdateView.as_view(), name='address_change'),
    path('delete/<int:pk>/',
         AddressDeleteView.as_view(), name='address_delete'),
    path('api/',include('addresses.addresses_api.routers')),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from core.utils import delete_item

from .views import TestView, ManageView
from products.views import IndexView
from core.functions import get_sb_data


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('manage/', ManageView.as_view(), name='manage'),
    path('search/', include('haystack.urls')),
    path('test/', TestView.as_view(), name='test'),
    path('sb_data/', get_sb_data, name='sb-data'),
    path('delete/', delete_item, name='delete'),
    path('products/', include('products.urls', namespace='products')),
    path('brands/', include('brands.urls', namespace='brands')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('tags/', include('tags.urls', namespace='tags')),
    path('addresses/', include('addresses.urls', namespace='addresses')),
    path('heroes/', include('heroes.urls', namespace='heroes')),
    path('logos/', include('logos.urls', namespace='logos')),
    path('media/', include('media.urls', namespace='media')),
    path('offers/', include('offers.urls', namespace='offers')),
    path('orders/', include('orders.urls', namespace='orders')),
  
    
    path('users/', include('users.urls')),
    path('profiles/', include('profiles.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-auth/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('api-token-auth/', obtain_jwt_token),
    # path('api-token-refresh/', refresh_jwt_token),
    #path('api-token-verify/', verify_jwt_token),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    try:
        import debug_toolbar
        urlpatterns += [
            path('__debug__', include(debug_toolbar.urls)),
        ]
    except ImportError:
        pass

backend/baskets/urls.py
from django.urls import path, include


app_name = 'baskets'

from .views import BasketView

from .functions import (
    remove_from_basket, add_to_basket, clear_basket,
    remove_item_from_basket, 
)


urlpatterns = [
    path('basket/items/', BasketView.as_view(), name='basket'),
    path('remove_from_basket/<int:id>/', remove_from_basket,
        name='remove_from_basket'),
    path('add_to_basket/<int:id>/', add_to_basket, name='add_to_basket'),
    path('remove_item_from_basket/<int:id>/', remove_item_from_basket,
         name='remove_item_from_basket'),
    path('clear/basket', clear_basket, name='clear-basket'),

    path('api/',include('baskets.baskets_api.routers')),
]

backend/orders/urls.py
from django.urls import path, include


from orders.views import *


app_name = 'orders'

urlpatterns = [
    path('',
         OrderListView.as_view(), name='order_list'),
    path('add/',
         OrderCreateView.as_view(), name='order_add'),
    path('view/<int:pk>/',
         OrderDetailView.as_view(), name='order_view'),
    path('change/<int:pk>/',
         OrderUpdateView.as_view(), name='order_change'),
    path('delete/<int:pk>/',
         OrderDeleteView.as_view(), name='order_delete'),
    path('model/order/', model_order, name='model_order'),
    path('api/',include('orders.orders_api.routers')),
]

backend/products/urls.py
from django.urls import path, include

from .views import *

from products.functions import *

app_name = 'products'

urlpatterns = [
    path('categories/',
         CategoryListView.as_view(), name='category_list'),
    path('categories/add/',
         CategoryCreateView.as_view(), name='category_add'),
    path('categories/<int:pk>/',
         CategoryDetailView.as_view(), name='category_view'),
    path('categories/change/<int:pk>/',
         CategoryUpdateView.as_view(), name='category_change'),
    path('categories/delete/<int:pk>/',
         CategoryDeleteView.as_view(), name='category_delete'),

    path('attributes/',
         AttributeListView.as_view(), name='attribute_list'),
    path('attributes/add/',
         AttributeCreateView.as_view(), name='attribute_add'),
    path('attributes/<int:pk>/',
         AttributeDetailView.as_view(), name='attribute_view'),
    path('attributes/change/<int:pk>/',
         AttributeUpdateView.as_view(), name='attribute_change'),
    path('attributes/delete/<int:pk>/',
         AttributeDeleteView.as_view(), name='attribute_delete'),


    path('features/',
         FeatureListView.as_view(), name='feature_list'),
    path('features/add/',
         FeatureCreateView.as_view(), name='feature_add'),
    path('features/<int:pk>/',
         FeatureDetailView.as_view(), name='feature_view'),
    path('features/change/<int:pk>/',
         FeatureUpdateView.as_view(), name='feature_change'),
    path('features/delete/<int:pk>/',
         FeatureDeleteView.as_view(), name='feature_delete'),

    path('products/',
         ProductListView.as_view(), name='product_list'),
    path('products/add/',
         ProductCreateView.as_view(), name='product_add'),
    path('products/<int:pk>/',
         ProductDetailView.as_view(), name='product_view'),
    path('products/change/<int:pk>/',
         ProductUpdateView.as_view(), name='product_change'),
    path('products/delete/<int:pk>/',
         ProductDeleteView.as_view(), name='product_delete'),



#     path('address/',
#          AddressListView.as_view(), name='address_list'),
#     path('address/add/',
#          AddressCreateView.as_view(), name='address_add'),
#     path('address/<int:pk>/',
#          AddressDetailView.as_view(), name='address_view'),
#     path('address/change/<int:pk>/',
#          AddressUpdateView.as_view(), name='address_change'),
#     path('address/delete/<int:pk>/',
#          AddressDeleteView.as_view(), name='address_delete'),


    
     
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('catalog/<int:pk>/', CatalogProductDetailView.as_view(),
         name='catalog-product-detail'),
    path('address/create/', SiteAddressCreateView.as_view(),
         name='site-address-add'),
    path('address/<int:pk>/update/', SiteAddressUpdateView.as_view(),
         name='site-address-update'),
    path('address/<int:pk>/delete/', SiteAddressDeleteView.as_view(),
         name='site-address-delete'),
    path('myorders/items/', OrderListView.as_view(), name='myorders'),
    path('order/items/', OrderFormView.as_view(), name='order'),
    path('search/', search_items, name="search"),

     path('sb/',get_products_for_sb, name='sb-products'),
     path('features/sb/',get_features_for_sb, name='sb-features'),
     path('categories/sb/',get_categories_for_sb, name='sb-categories'),
     path("delete/media/<int:product_id>/<int:media_id>/",delete_media,name='form-delete-media'),
     path("delete/logo/<int:product_id>/<int:logo_id>/",delete_logo,name='form-delete-logo'),
     path("delete/attribute/<int:product_id>/<int:attribute_id>/",delete_attribute,name='form-delete-attribute'),
     path("create/attribute/<int:product_id>/",create_product_attribute,name='form-create-attribute'),
     path("generate_pdf/<int:product_id>/",generate_pdf,name='generate-pdf'),

     path("create/feature/attribute/<int:feature_id>/",create_feature_attribute, name="add-feature-attribute"),


    path('api/',include('products.productsapi.routers')),
]

backend/tags/urls.py
from django.urls import path, include


from tags.views import *

from .functions import get_tags_for_sb

app_name = 'tags'
urlpatterns = [
    path('',
         TagListView.as_view(), name='tag_list'),
    path('add/',
         TagCreateView.as_view(), name='tag_add'),
    path('view/<int:pk>/',
         TagDetailView.as_view(), name='tag_view'),
    path('change/<int:pk>/',
         TagUpdateView.as_view(), name='tag_change'),
    path('delete/<int:pk>/',
         TagDeleteView.as_view(), name='tag_delete'),
    
    path('get_tags_for_sb/', get_tags_for_sb, name='get_tags_for_sb'),
    path('api/',include('tags.tags_api.routers')),
]

backend/addresses/models.py
from django.db import models

# Create your models here.
from core.models import Timestamped


class Address(Timestamped):
    SHIPPING_ADDRESS, BILLING_ADDRESS = range(0, 2)
    ADDRESS_CHOICES = (
        (SHIPPING_ADDRESS, 'Shipping Address'),
        (BILLING_ADDRESS, 'Billing Address')
    )
    address_type = models.PositiveIntegerField(choices=ADDRESS_CHOICES)
    profile = models.ForeignKey('profiles.Profile', on_delete=models.CASCADE,
                                null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)
    street_name = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    street_number = models.PositiveIntegerField()
    floor_number = models.PositiveIntegerField()

    class Meta:
        default_related_name = 'addresses'
        verbose_name = 'address'
        verbose_name_plural = 'addresses'

    def __str__(self):
        return f"{self.first_name},{self.last_name}"

backend/addresses/forms.py
from django import forms
from django.forms import inlineformset_factory

from core.forms import BootstrapForm, BootstrapFormSet

from .models import Address


class AddressForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = Address
        fields = ('profile', 'address_type',  'first_name', 'last_name',
                  'mobile', 'street_name', 'postal_code', 'city',
                  'street_number', 'floor_number')

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super().__init__(*args, **kwargs)


class SiteAddressForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = Address
        fields = ('first_name', 'last_name',
                  'mobile', 'street_name', 'postal_code', 'city',
                  'street_number', 'floor_number')

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

backend/orders/forms.py
from django import forms
from django.forms import inlineformset_factory

from core.forms import BootstrapForm, BootstrapFormSet

from addresses.models import Address


from .models import Order, OrderItem


class OrderForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = Order
        fields = ('order_registration', 'billing_address', 'shipping_address',
                  'total', 'comments')

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        super().__init__(*args, **kwargs)


class SiteOrderForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = Order
        fields = ('billing_address', 'shipping_address',
                  'comments')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)
        self.fields['billing_address'].queryset = Address.objects.select_related(
            'profile').filter(profile_id=self.request.user.profile.pk,
                              address_type=Address.BILLING_ADDRESS)
        self.fields['shipping_address'].queryset = Address.objects.select_related(
            'profile').filter(profile_id=self.request.user.profile.pk,
                              address_type=Address.SHIPPING_ADDRESS)


class OrderItemForm(BootstrapForm, forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ('order', 'product', 'quantity')


OrderItemFormSet = inlineformset_factory(Order, OrderItem,
                                         form=OrderItemForm,
                                         formset=BootstrapFormSet,
                                         can_delete=True,
                                         fk_name='order')

backend/addresses/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Prefetch
from django.shortcuts import render
from django.apps import apps

from core.views import (
    BaseListView, BaseDetailView,
    BaseCreateView, BaseUpdateView, BaseDeleteView
)

from addresses.models import Address

from addresses.forms import AddressForm


class AddressListView(BaseListView):
    model = Address
    paginate_by = 50
    fields = [
        {
        'verbose_name': 'First Name',
        'db_name':'first_name'
        },
        {
        'verbose_name': 'Last Name',
        'db_name':'last_name'
        },
        {
        'verbose_name': 'Mobile',
        'db_name':'mobile'
        },
    ]


class AddressDetailView(BaseDetailView):
    model = Address


class AddressCreateView(BaseCreateView):
    model = Address
    form_class = AddressForm


class AddressUpdateView(BaseUpdateView):
    model = Address
    form_class = AddressForm


class AddressDeleteView(BaseDeleteView):
    model = Address

backend/orders/views.py
import json
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Prefetch
from django.shortcuts import render
from django.apps import apps

from core.views import (
    BaseListView, BaseDetailView,
    BaseCreateView, BaseUpdateView, BaseDeleteView
)

from core.functions import is_ajax


from orders.models import Order


from orders.forms import OrderForm


class OrderListView(BaseListView):
    model = Order
    paginate_by = 50
    fields = [
        {
        'verbose_name': 'Billing Address',
        'db_name':'billing_address'
        },
    ]


class OrderDetailView(BaseDetailView):
    model = Order


class OrderCreateView(BaseCreateView):
    model = Order
    form_class = OrderForm


class OrderUpdateView(BaseUpdateView):
    model = Order
    form_class = OrderForm


class OrderDeleteView(BaseDeleteView):
    model = Order


def model_order(request):
    if request.method == 'POST' and is_ajax(request):
        model_name = request.POST['model_name']
        app_name = request.POST['app_name']
        model = apps.get_model(app_name, model_name)
        page_id_array = json.loads(request.POST['page_id_array'])
        objs = []
        for index, item in enumerate(page_id_array):
            # if model_name == 'childcategory':
            #     obj = model.objects.get(target=item["pk"],source=item['parent'])
            # elif model_name == 'attributefeature':
            #     obj = model.objects.get(feature=item)
            # elif model_name == 'brandsupplier':
            #     obj = model.objects.get(supplier=item)
            # elif model_name == 'featurecategory':
            #     obj = model.objects.get(category=item)
            # else:
            obj = model.objects.get(pk=item["pk"])
            obj.order = index
            objs.append(obj)
            # obj.save()
        model.objects.bulk_update(objs, ['order'])
        return JsonResponse(page_id_array, safe=False)
    return HttpResponse('')

backend/templates/site/navbar.html
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% url 'index' as index_url %}
    {% url 'baskets:basket' as basket_url %}
    <a class="navbar-brand" href="{{index_url}}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#" id="mega-menu-1">Categories</a>
        </li>
        <li class="nav-item {% if request.path == basket_url %}active {% endif %}">
            <a class="nav-link ajax_basket" href="{{basket_url}}">
              <i class="bi bi-cart"></i>
               <span class="badge bg-light text-dark">
                  {{basket_count}}
               </span>
          </a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="#" id="mega-menu-2">Brands</a>
        </li>
      </ul>
      <form class="d-flex  me-auto flex-grow-1" action="{% url 'products:catalog' %}">
        <div class="ui-widget">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" id="search" aria-label="Search">
        </div>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <ul class="navbar-nav">
        {% if not request.user.is_anonymous %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-fill"></i>{{request.user}}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <form action="{% url 'logout' %}" method="post" class="dropdown-item">
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
            
            

            <a class="dropdown-item" href="{% url 'products:myorders' %}">My orders</a>
            <a class="dropdown-item" href="{% url 'profile-detail' request.user.profile.pk %}">My Profile</a>
            {% if request.user.is_superuser %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'manage' %}">Manage</a>
          </div>
          {% endif %}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

backend/templates/site/product_detail.html
{% extends "site/base.html" %}
{% load static %}
{% load core %}

{% block head %}
    <style>

        .swiper {
            width: 100%;
            height: 100%;
        }

        .swiper-slide {
            text-align: center;
            font-size: 18px;
            background: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .swiper-slide img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .swiper {
            width: 100%;
            height: 300px;
            margin-left: auto;
            margin-right: auto;
        }

        .swiper-slide {
            background-size: cover;
            background-position: center;
        }

        .mySwiper2 {
            height: 80%;
            width: 100%;
        }

        .mySwiper {
            height: 20%;
            box-sizing: border-box;
            padding: 10px 0;
        }

        .mySwiper .swiper-slide {
            width: 25%;
            height: 100%;
            opacity: 0.4;
        }

        .mySwiper .swiper-slide-thumb-active {
            opacity: 1;
        }

        .swiper-slide img {
            display: block;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

    </style>
{% endblock %}



{% block content %}

    <div class="container-fluid wrapper rounded shadow">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                      <li class="breadcrumb-item"><a href="{% url 'products:catalog' %}?category={{ object.category.id }}">{{ object.category.name }}</a></li>
                      <li class="breadcrumb-item active" aria-current="page">{{object.name}}</li>
                    </ol>
                  </nav>
            </div> <!--col-->
        </div> <!--row-->
        <div class="row">
            <div class="col">
                <h1 style="font-size:25px;">{{ object.name }}</h1>
            </div><!--col-->
        </div> <!-- row-->
        <div class="row">
            <div class="col-4">
                {% if object.productmedia.all.count > 0 %}
                <div style="--swiper-navigation-color: #000; --swiper-pagination-color: #000"
                     class="swiper mySwiper2">
                    <div class="swiper-wrapper">
                        {% for media in object.productmedia.all %}
                            <div class="swiper-slide">
                                {% if media.media.image %}
                                    <img src="{{ media.media.image.url }}">
                                {% else %}
                                    <img src="{{media.media.url}}" alt="">
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
                <div thumbsSlider="" class="swiper mySwiper">
                    <div class="swiper-wrapper">
                        {% for media in object.productmedia.all %}
                            <div class="swiper-slide">
                                {% if media.media.image %}
                                <img src="{{ media.media.image.url }}">
                            {% else %}
                                <img src="{{media.media.url}}" alt="">
                            {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            
            {% elif object.image %}
            <img src="{{ object.image.url }}" class="img-fluid">
            {% elif object.image_url %}
            <img src="{{object.image_url}}" class="img-fluid" >
            {% else %}
            <img src="/static/img/default.jpg" class="img-fluid" >
            {% endif %}
            


                {% if object.tags.all %}
                    <div class="">
                        {% for tag in object.tags.all %}
                            <a class="tag-link"
                            href="{% url 'products:catalog' %}?tag={{ tag.id }}">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                {% endif %}
            </div> <!--col 4 div swiper-->
            <div class="col-8">
                <div>
                    
                    <a href="{% url 'products:catalog' %}?brand={{ object.brand.pk }}" class="tag-link">
                        {% if object.brand.image %}
                            <img src="{{ object.brand.image.url }}" alt="" class="img-fluid">
                        {% else %}
                            {{ object.brand }}
                        {% endif %}
                    </a>
                </div>
                <div>
                    <div class="d-flex justify-content-end">
                        {% if object.pdf_guide %}
                            <a href="{{ object.pdf_guide.url }}" class="justify-content-end"><i
                                    class="bi bi-file-pdf-fill"
                                    style="font-size:2.4rem;"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div>
                    <div class="text-end col-2">
                        <a href="{% url 'baskets:add_to_basket' object.id %}" class="btn btn-primary ajax_add_to_cart"><i
                                class=" bi bi-cart"></i> {% format_currency object.price %}</a>
                    </div>

                </div>

                    {% if  object.productlogos.all %}
                    <div class="row mt-2 ">
                        {% for logo in object.productlogos.all %}
                            {% if logo.logo.image %}
                                <div class="col-2">
                                    <img src="{{ logo.logo.image.url }}" alt="" class="img-fluid">

                                </div>
                            {% else %}
                            <div class="col-2">
                                <img src="{{ logo.logo.url }}" alt="" class="img-fluid">
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <hr>
                {% endif %}
           <div> <!--class 8 div-->
           </div>
        </div> <!--row-->
        <div class="row">
            <div class="col">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="description-tab" data-bs-toggle="tab"
                                data-bs-target="#description-tab-pane" type="button" role="tab"
                                aria-controls="description-tab-pane" aria-selected="true">Description
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="specs-tab" data-bs-toggle="tab" data-bs-target="#specs-tab-pane"
                                type="button" role="tab" aria-controls="specs-tab-pane" aria-selected="false">Specs
                        </button>
                    </li>
                    {% if  object.relatedproducts.all %}
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="compatible-tab" data-bs-toggle="tab"
                                    data-bs-target="#compatible-tab-pane" type="button" role="tab"
                                    aria-controls="compatible-tab-pane" aria-selected="false">Compatible
                            </button>
                        </li>
                    {% endif %}
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="description-tab-pane" role="tabpanel"
                         aria-labelledby="description-tab" tabindex="0">
                        <div class="">
                            {{ object.description|safe }}
                        </div>


                    </div> <!--description-->
                    <div class="tab-pane fade" id="specs-tab-pane" role="tabpanel" aria-labelledby="specs-tab"
                         tabindex="0">
                        <div class="d-flex flex-row">
                            <div class="col-6">
                                <table class="table table-striped">
                                    <tbody>
                                    {% for attr in object.attributes.all %}
                                        <tr>
                                            <td>{{ attr.feature }}</td>
                                            <td>{{ attr|safe }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>


                    </div> <!--specs-->
                    {% if  object.relatedproducts.all %}
                        <div class="tab-pane fade" id="compatible-tab-pane" role="tabpanel"
                             aria-labelledby="compatible-tab" tabindex="0">...
                            <div class="row">
                                {% for item in object.relatedproducts.all %}
                                    <div class="col">
                                        <div class="card">
                                            {% if item.image %}
                                                <img src="{{ item.image.url }}" class="card-img-top" alt="...">
                                            {% endif %}
                                            <div class="card-body">
                                                <h6 class="card-title">{{ item }}</h6>
                                                <a href="{% url 'products:catalog-product-detail' item.pk %}"
                                                   class="btn btn-primary">Info</a>
                                            </div>
                                        </div>
                                    </div>

                                {% endfor %}
                            </div>


                        </div> <!--compatible-->
                    {% endif %}

                </div>
            </div>


        </div>
    

{% endblock %}

{% block body_scripts %}

    <script>
        'use strict';

        (function (w, d, $) {
            $(d).ready(function () {
                var swiper = new Swiper(".mySwiper", {
                    spaceBetween: 5,
                    slidesPerView: 6,
                    freeMode: true,
                    watchSlidesVisibility: true,
                    watchSlidesProgress: true,
                });
                var swiper2 = new Swiper(".mySwiper2", {
                    loop: true,
                    spaceBetween: 10,
                    navigation: {
                        nextEl: ".swiper-button-next",
                        prevEl: ".swiper-button-prev",
                    },
                    thumbs: {
                        swiper: swiper,
                    },
                });


            })

        })(window, document, jQuery)


    </script>





{% endblock %}

backend/templates/site/product_list.html
{% extends "site/base.html" %}
{% load static  %}
{% block content %}
<div class="container">
      <div class="res">
        {% include 'products/partials/_product_ajax_list.html' %}
      </div>
</div>

{% endblock %}